<?php

/**
 * Credit Card Validation Solution, PHP Edition,
 * Hebrew language error messages. By Yaron Arama June 2015
 *
 * @package    CreditCardValidationSolution
 * @author     Daniel Convissor <danielc@analysisandsolutions.com>
 * @copyright  The Analysis and Solutions Company, 2002-2006
 * @version    $Name: rel-5-14 $ $Id: ccvs_en.inc,v 1.3 2006-03-18 17:31:31 danielc Exp $
 * @link       http://www.analysisandsolutions.com/software/ccvs/ccvs.htm
 */

/** */
$CCVSErrNumberString = 'המספר אינו מחרוזת';
$CCVSErrVisa14       = 'כרטיס מסוג ויזה מכיל בדרך כלל 13 או 16 ספרות, את/ה הכנסת 14';
$CCVSErrUnknown      = 'ארבע הספרות הראשונות, %s, מצביעות על כרטיס שאינו מזוהה';
$CCVSErrAccepted     = 'Programmer improperly used the Accepted argument';
$CCVSErrNoAccept     = 'אנו לא מכבדים כרטיס מסוג  %s ';
$CCVSErrShort        = 'למספר כרטיס האשראי חסרות %s ספרות';
$CCVSErrLong         = 'למספר %s יותר מדיי ספרות';
$CCVSErrChecksum     = 'מספר הכרטיס שגוי';
$CCVSErrMonthString  = 'חודש אינו יכול להיות מחרוזת';
$CCVSErrMonthFormat  = 'החודש בפורמט שגוי';
$CCVSErrYearString   = 'השנה אינה יכולה להיות מחרוזת';
$CCVSErrYearFormat   = 'השנה בפורמט שגוי';
$CCVSErrExpired      = 'הכרטיס פג תוקף';

