<?php

/**
 * Credit Card Validation Solution, PHP Edition,
 * Lithuanian language error messages.
 *
 * @package    CreditCardValidationSolution
 * @author     Daniel Convissor <danielc@analysisandsolutions.com>
 * @copyright  The Analysis and Solutions Company, 2002-2006
 * @version    $Name: rel-5-14 $ $Id: ccvs_en.inc,v 1.3 2006-03-18 17:31:31 danielc Exp $
 * @link       http://www.analysisandsolutions.com/software/ccvs/ccvs.htm
 */

/** */
$CCVSErrNumberString = 'Skaičius nėra seka';
$CCVSErrVisa14       = 'Visa paprastai naudoja 16 arba 13 skaitmenų, bet jūs įvedėte 14';
$CCVSErrUnknown      = 'Pirmi keturi skaitmenys, %s, indikuoja, kad neatpažintas kortelės tipas';
$CCVSErrAccepted     = 'Programuotojas netinkamai panaudojo argumentą Priimta';
$CCVSErrNoAccept     = 'Mes nepriimame %s kortelių';
$CCVSErrShort        = 'Įvestame numeryje trūksta %s skaičių(iaus)';
$CCVSErrLong         = 'Įvestame numeryje %s skaitmenimis(iu) per daug';
$CCVSErrChecksum     = 'Numeris nepraėjo kortelės kontrolės testo';
$CCVSErrMonthString  = 'Month isn\'t a string';
$CCVSErrMonthFormat  = 'Mėnesio formatas netinkamas';
$CCVSErrYearString   = 'Year isn\'t a string';
$CCVSErrYearFormat   = 'Metų formatas netinkamas';
$CCVSErrExpired      = 'Kortelė nebegalioja';
